version: '3.9'

services:
  server:
    image: ketjo/ez-shops:latest
    container_name: ez-shops
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    restart: always
  database:
    image: mongo:5.0.0
    container_name: ez-shops_database
    ports:
      - '${DATABASE_PORT}:27017'
    restart: always
