version: '3.9'

services:
  db:
    image: mongo:5.0.0
    container_name: db
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    restart: always
  server:
    image: ketjo/k-passport:latest
    container_name: k-passport
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    restart: always
    links:
      - 'db'