version: '3.9'

services:
  db:
    image: mongo:5.0.0
    container_name: db
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    restart: always
  server:
    image: ghcr.io/erlan-zharkeev/k-passport:latest
    container_name: k-passport
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.development
    environment:
      DATABASE_URI: mongodb://db:${DATABASE_PORT}/db
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    restart: always
    depends_on:
      - db
