/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "auth": {
        "loginSuccess": string;
        "invalidPassword": string;
        "failedToValidatePassword": string;
    };
    "common": {
        "undefinedError": string;
    };
    "user": {
        "registered": string;
        "notFound": string;
        "passwordHashFailed": string;
        "failedToSaveToDb": string;
        "failedToGetUserData": string;
        "failedToCheckUserExist": string;
        "userWithProvidedCredentialsAlreadyExist": string;
        "failedToUpdateRefreshToken": string;
        "emailConfirmation": string;
        "failedToSendEmailConfirmationLink": string;
        "failedToMarkEmailAsConfirmed": string;
        "emailConfirmed": string;
        "emailNotConfirmed": string;
        "failedToSaveCode": string;
        "resetPassword": string;
        "failedToUpdatePassword": string;
        "codeInvalid": string;
        "failedToCompareCode": string;
        "passwordUpdateSuccess": string;
        "linkToResetPasswordSent": string;
        "failedToSendCode": string;
        "codeIsExpired": string;
        "failedToGetCode": string;
        "codeCantBeSend": string;
    };
    "validation": {
        "usernameMustNotConsistSigns": string;
        "codeIsShort": string;
        "emailIncorrect": string;
        "usernameLengthOutOfRange": string;
        "isNotAString": string;
        "passwordLengthOutOfRange": string;
        "passwordNotMatchRegexp": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
